import event1 from "@/assets/images/image.png";

export const events = [
  {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
    {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
      {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },
      {
    title: "Ella's birthday",
    card: event1,
    date: "26/11/2025",
    time: "2:00 pm",
    description:"its ella's 12 birthday, JOIN NOW!!",
    location: "My house",
    capacity: 20,
    href: "/ellasbirthday",
    slug: "ellasbirthday",
    attendees: ["fiyin", "ella", "tara"],
  },

];
